#cloud-config
write_files:
- path: /etc/nixos/host.nix
  permissions: '0644'
  content: |
    { pkgs, config, lib, ... }:
    {
      environment.systemPackages = with pkgs; [
        lf # file manager
        ripgrep # better grep
        fd # better find
        bottom # better htop
        lsof
        nil # for nix ide
        nixpkgs-fmt # for nix ide
        vim
      ];

      services.tailscale.enable = true;
      services.tailscale.useRoutingFeatures = "server";
      networking.firewall = {
        enable = true;
        allowedTCPPorts = [ ];
        allowedUDPPorts = [ config.services.tailscale.port ];
        allowPing = lib.mkForce false;
        trustedInterfaces = [ "tailscale0" ];
      };

      services.openssh.enable = true;
      services.openssh.openFirewall = true;
      services.openssh.settings.PasswordAuthentication = false;

      programs.git.enable = true;
    }
runcmd:
  - curl https://raw.githubusercontent.com/elitak/nixos-infect/master/nixos-infect | PROVIDER=digitalocean NIXOS_IMPORT=./host.nix NIX_CHANNEL=nixos-23.11 bash 2>&1 | tee /tmp/infect.log
